# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run  
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Builda:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install hashcat && hashcat -m 0 -a 3 -w 4 -O 'b8b1a1c7983257a7c2ce77c6d28f417b' 'a?l?l?l?l?l?l?l?l?l?l'
  Buildb:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install hashcat && hashcat -m 0 -a 3 -w 4 -O 'b8b1a1c7983257a7c2ce77c6d28f417b' 'b?l?l?l?l?l?l?l?l?l?l'
  Buildc:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install hashcat && hashcat -m 0 -a 3 -w 4 -O 'b8b1a1c7983257a7c2ce77c6d28f417b' 'c?l?l?l?l?l?l?l?l?l?l'
  Buildd:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install hashcat && hashcat -m 0 -a 3 -w 4 -O 'b8b1a1c7983257a7c2ce77c6d28f417b' 'd?l?l?l?l?l?l?l?l?l?l'
  Builde:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install hashcat && hashcat -m 0 -a 3 -w 4 -O 'b8b1a1c7983257a7c2ce77c6d28f417b' 'e?l?l?l?l?l?l?l?l?l?l'
  Buildf:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install hashcat && hashcat -m 0 -a 3 -w 4 -O 'b8b1a1c7983257a7c2ce77c6d28f417b' 'f?l?l?l?l?l?l?l?l?l?l'
  Buildg:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install hashcat && hashcat -m 0 -a 3 -w 4 -O 'b8b1a1c7983257a7c2ce77c6d28f417b' 'g?l?l?l?l?l?l?l?l?l?l'
  Buildh:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install hashcat && hashcat -m 0 -a 3 -w 4 -O 'b8b1a1c7983257a7c2ce77c6d28f417b' 'h?l?l?l?l?l?l?l?l?l?l'
  Buildi:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install hashcat && hashcat -m 0 -a 3 -w 4 -O 'b8b1a1c7983257a7c2ce77c6d28f417b' 'i?l?l?l?l?l?l?l?l?l?l'
  Buildj:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install hashcat && hashcat -m 0 -a 3 -w 4 -O 'b8b1a1c7983257a7c2ce77c6d28f417b' 'j?l?l?l?l?l?l?l?l?l?l'
  Buildk:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install hashcat && hashcat -m 0 -a 3 -w 4 -O 'b8b1a1c7983257a7c2ce77c6d28f417b' 'k?l?l?l?l?l?l?l?l?l?l'
  Buildl:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install hashcat && hashcat -m 0 -a 3 -w 4 -O 'b8b1a1c7983257a7c2ce77c6d28f417b' 'l?l?l?l?l?l?l?l?l?l?l'
  Buildm:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install hashcat && hashcat -m 0 -a 3 -w 4 -O 'b8b1a1c7983257a7c2ce77c6d28f417b' 'm?l?l?l?l?l?l?l?l?l?l'
  Buildn:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install hashcat && hashcat -m 0 -a 3 -w 4 -O 'b8b1a1c7983257a7c2ce77c6d28f417b' 'n?l?l?l?l?l?l?l?l?l?l'
  Buildo:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install hashcat && hashcat -m 0 -a 3 -w 4 -O 'b8b1a1c7983257a7c2ce77c6d28f417b' 'o?l?l?l?l?l?l?l?l?l?l'
  Buildp:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install hashcat && hashcat -m 0 -a 3 -w 4 -O 'b8b1a1c7983257a7c2ce77c6d28f417b' 'p?l?l?l?l?l?l?l?l?l?l'
  Buildq:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install hashcat && hashcat -m 0 -a 3 -w 4 -O 'b8b1a1c7983257a7c2ce77c6d28f417b' 'q?l?l?l?l?l?l?l?l?l?l'
  Buildr:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install hashcat && hashcat -m 0 -a 3 -w 4 -O '5b8b1a1c7983257a7c2ce77c6d28f417b' 'r?l?l?l?l?l?l?l?l?l?l'
  Builds:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install hashcat && hashcat -m 0 -a 3 -w 4 -O 'b8b1a1c7983257a7c2ce77c6d28f417b' 's?l?l?l?l?l?l?l?l?l?l'
  Buildt:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install hashcat && hashcat -m 0 -a 3 -w 4 -O 'b8b1a1c7983257a7c2ce77c6d28f417b' 't?l?l?l?l?l?l?l?l?l?l'
  Buildu:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install hashcat && hashcat -m 0 -a 3 -w 4 -O 'b8b1a1c7983257a7c2ce77c6d28f417b' 'u?l?l?l?l?l?l?l?l?l?l'
  Buildv:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install hashcat && hashcat -m 0 -a 3 -w 4 -O 'b8b1a1c7983257a7c2ce77c6d28f417b' 'v?l?l?l?l?l?l?l?l?l?l'
  Buildw:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install hashcat && hashcat -m 0 -a 3 -w 4 -O 'b8b1a1c7983257a7c2ce77c6d28f417b' 'w?l?l?l?l?l?l?l?l?l?l'
  Buildx:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install hashcat && hashcat -m 0 -a 3 -w 4 -O 'b8b1a1c7983257a7c2ce77c6d28f417b' 'x?l?l?l?l?l?l?l?l?l?l'
  Buildy:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install hashcat && hashcat -m 0 -a 3 -w 4 -O 'b8b1a1c7983257a7c2ce77c6d28f417b' 'y?l?l?l?l?l?l?l?l?l?l'
  Buildz:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install hashcat && hashcat -m 0 -a 3 -w 4 -O 'b8b1a1c7983257a7c2ce77c6d28f417b' 'z?l?l?l?l?l?l?l?l?l?l'
    
